# Generated by Django 6.0.4 on 2026-04-27 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DEPOSIT_CONFIRMED', 'Deposit Confirmed'), ('WITHDRAWAL_APPROVED', 'Withdrawal Approved'), ('WITHDRAWAL_COMPLETED', 'Withdrawal Completed'), ('WITHDRAWAL_REJECTED', 'Withdrawal Rejected'), ('INVESTMENT_CREATED', 'Investment Created'), ('INVESTMENT_COMPLETED', 'Investment Completed'), ('ROI_CREDITED', 'ROI Credited'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
