# Generated by Django 6.0.4 on 2026-04-27 10:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('TRC20', 'TRON (TRC-20)'), ('ERC20', 'Ethereum (ERC-20)'), ('BEP20', 'BSC (BEP-20)')], default='TRC20', max_length=10)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('balance', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'network')},
            },
        ),
    ]
