# Generated by Django 6.0.4 on 2026-04-27 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_HOLD', 'Withdrawal Hold'), ('WITHDRAWAL_REFUND', 'Withdrawal Refund'), ('INVESTMENT', 'Investment'), ('INVESTMENT_RETURN', 'Investment Return'), ('ROI', 'Daily ROI'), ('TRANSFER', 'Internal Transfer'), ('FEE', 'Platform Fee'), ('BONUS', 'Bonus / Referral')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
