# Generated by Django 6.0.4 on 2026-04-27 10:11

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('tx_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('from_address', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=10)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('required_confirmations', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMING', 'Confirming on Chain'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
