# Generated by Django 6.0.4 on 2026-04-27 10:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=6, default=Decimal('10.000000'), max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=6, default=Decimal('100000.000000'), max_digits=20)),
                ('daily_roi_percent', models.DecimalField(decimal_places=3, default=Decimal('0.500'), max_digits=6)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Investment Plan',
                'verbose_name_plural': 'Investment Plans',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('daily_earning', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('days_completed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='investments.investmentplan')),
            ],
            options={
                'verbose_name': 'User Investment',
                'verbose_name_plural': 'User Investments',
                'ordering': ['-created_at'],
            },
        ),
    ]
